### ISSUE TITLE
Composer install returning error while installing it on php 8.1

### ISSUE THREAD

**Issue by SachinBahukhandi** [kalimatas/php-liquid#174]
I tried forking the package and running `composer install` returns the following trace:

```
PHP Fatal error:  Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer/src/Composer/Config.php:191
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Config.php(191): array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(350): Composer\Config->merge()
#2 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#3 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(445): Composer\Factory::create()
#4 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65): Composer\Console\Application->getComposer()
#5 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(150): Composer\Command\BaseCommand->getComposer()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(211): Composer\Command\BaseCommand->initialize()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#9 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#10 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#11 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#12 phar:///usr/local/bin/composer/bin/composer(83): Composer\Console\Application->run()
#13 /usr/local/bin/composer(29): require('...')
#14 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Config.php on line 191

Fatal error: Uncaught TypeError: array_merge(): Argument #1 must be of type array, bool given in phar:///usr/local/bin/composer/src/Composer/Config.php:191
Stack trace:
#0 phar:///usr/local/bin/composer/src/Composer/Config.php(191): array_merge()
#1 phar:///usr/local/bin/composer/src/Composer/Factory.php(350): Composer\Config->merge()
#2 phar:///usr/local/bin/composer/src/Composer/Factory.php(643): Composer\Factory->createComposer()
#3 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(445): Composer\Factory::create()
#4 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(65): Composer\Console\Application->getComposer()
#5 phar:///usr/local/bin/composer/src/Composer/Command/BaseCommand.php(150): Composer\Command\BaseCommand->getComposer()
#6 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(211): Composer\Command\BaseCommand->initialize()
#7 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run()
#8 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand()
#9 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(336): Symfony\Component\Console\Application->doRun()
#10 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun()
#11 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(131): Symfony\Component\Console\Application->run()
#12 phar:///usr/local/bin/composer/bin/composer(83): Composer\Console\Application->run()
#13 /usr/local/bin/composer(29): require('...')
#14 {main}
  thrown in phar:///usr/local/bin/composer/src/Composer/Config.php on line 191
```

**Comment by sanmai** [comment]
Looking at the stack trace, where do you see this package mentioned?

**Comment by SachinBahukhandi** [comment]
> Looking at the stack trace, where do you see this package mentioned?

I just tried forking it and running a plain composer install returned this error.
Isn't this enough to tell that there is an error coming up.
Also, Here it has been discussed: https://github.com/composer/composer/issues/10907
And, the issue seems to be caused by this line in `composer.json`:
```
"config": {
        "sort-packages": true,
        "allow-plugins": true
    },
```

**Comment by sanmai** [comment]
This package has nothing to do with the problem you have. Try updating Composer.
